# -*- coding: utf-8 -*-
"""campaignAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fBQYmdDo2aPbU5l7-8vbY2fcCnEOVFff
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/Order_Data_meriskill.csv", low_memory=False)

df.head()

# Convert columns to numeric safely
def to_number(x):
    if pd.isna(x): return np.nan
    x = str(x).replace("£","").replace("$","").replace(",","").strip()
    try: return float(x)
    except: return np.nan

df["ProductPrice"] = df["ProductPrice"].apply(to_number)
df["ProductCost"]  = df["ProductCost"].apply(to_number)
df["OrderQuantity"] = pd.to_numeric(df["OrderQuantity"], errors="coerce")

import numpy as np
import pandas as pd

# --- Diagnose current types (optional but helpful)
print(df.dtypes)          # see which columns are "object" (text)
print(df.columns.tolist())  # confirm exact column names

# --- Helper: convert messy currency/number text -> float
def to_num(x):
    if pd.isna(x):
        return np.nan
    s = str(x)
    # remove common currency symbols and thousand separators
    s = s.replace("£","").replace("$","").replace(",","").strip()
    # remove any stray non-numeric characters (keeps digits, dot, minus)
    s = pd.Series([s]).str.replace(r"[^0-9\.\-]", "", regex=True).iloc[0]
    # empty string -> NaN
    if s == "" or s == "." or s == "-":
        return np.nan
    try:
        return float(s)
    except:
        return np.nan

# --- Make sure the three key columns are numeric
for col in ["ProductPrice", "ProductCost", "OrderQuantity"]:
    # If your file uses different names, adjust here accordingly
    df[col] = df[col].apply(to_num)

# (Optional) sanity check
print(df[["ProductPrice","ProductCost","OrderQuantity"]].head())

# --- STEP 3: Compute metrics safely
df["Revenue"] = df["ProductPrice"] * df["OrderQuantity"]
df["Cost"]    = df["ProductCost"]  * df["OrderQuantity"]
df["Margin"]  = df["Revenue"] - df["Cost"]

# Quick preview to confirm it worked
df[["OrderID","ProductPrice","OrderQuantity","Revenue","Cost","Margin"]].head()

#Group by campaign / acquisition source
campaign = df.groupby("AcquisitionSource").agg(
    Orders=("OrderID", "nunique"),
    Customers=("CustID", "nunique"),
    Revenue=("Revenue", "sum"),
    Cost=("Cost", "sum"),
    Margin=("Margin", "sum"),
    Avg_Order_Value=("Revenue", lambda x: x.sum() / len(x))
).reset_index()

campaign["Margin_%"] = (campaign["Margin"] / campaign["Revenue"]) * 100
campaign.sort_values("Margin", ascending=False)

#Create charts

import matplotlib.pyplot as plt

# --- Bar chart: revenue per campaign
plt.figure(figsize=(8,5))
plt.bar(campaign["AcquisitionSource"], campaign["Revenue"])
plt.title("Total Revenue by Campaign")
plt.xlabel("Campaign")
plt.ylabel("Revenue (£)")
plt.xticks(rotation=45)
plt.show()

#quick score to choose your single campaign

campaign["Score"] = campaign["Margin"] / campaign["Revenue"].max()
best = campaign.sort_values("Score", ascending=False).head(1)
best

fraud_rate = df.groupby("AcquisitionSource")["Fraud"].apply(lambda x: (x=="YES").mean()*100)
campaign = campaign.merge(fraud_rate, on="AcquisitionSource", how="left")
campaign.rename(columns={"Fraud":"Fraud_Rate_%"} , inplace=True)
campaign

import matplotlib.pyplot as plt
import pandas as pd

# Make sure OrderDate is in datetime format
df["OrderDate"] = pd.to_datetime(df["OrderDate"], errors="coerce")

# Drop rows where OrderDate is missing
df = df.dropna(subset=["OrderDate"])

# Extract the week start (e.g. every Monday)
df["Week"] = df["OrderDate"].dt.to_period("W").apply(lambda r: r.start_time)

# Group by week and campaign
weekly = (
    df.groupby(["Week", "AcquisitionSource"])
      .agg(Revenue=("Revenue", "sum"))
      .reset_index()
)

# Pivot for plotting
weekly_pivot = weekly.pivot(index="Week", columns="AcquisitionSource", values="Revenue").fillna(0)

# --- Plot
plt.figure(figsize=(10,6))
for campaign in weekly_pivot.columns:
    plt.plot(weekly_pivot.index, weekly_pivot[campaign], label=campaign)

plt.title("Weekly Revenue Trends by Campaign", fontsize=14)
plt.xlabel("Week")
plt.ylabel("Revenue (£)")
plt.legend(title="Campaign")
plt.grid(True)
plt.tight_layout()
plt.show()

# Calculate total margin percentage per campaign
margin_summary = (
    df.groupby("AcquisitionSource")
      .agg(Revenue=("Revenue","sum"), Margin=("Margin","sum"))
      .reset_index()
)
margin_summary["Margin_%"] = (margin_summary["Margin"] / margin_summary["Revenue"]) * 100

# --- Plot
plt.figure(figsize=(8,5))
plt.bar(margin_summary["AcquisitionSource"], margin_summary["Margin_%"], color="skyblue")
plt.title("Profit Margin % by Campaign", fontsize=14)
plt.xlabel("Campaign")
plt.ylabel("Profit Margin (%)")
plt.xticks(rotation=30)
plt.tight_layout()
plt.show()